## use to store all the parameters of the model at one place. Don't need to open model trainer file and chnage the parameters.

TrainingArguments:
  num_train_epochs: 3
  warmup_steps: 500
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  weight_decay: 0.01
  logging_steps: 10
  evaluation_strategy: 'steps'
  eval_steps: 500
  save_steps: 1e6
  gradient_accumulation_steps: 16